"""add_dynamic_attributes_and_process_enum

Revision ID: 21b45f046656
Revises: f69e15463d05
Create Date: 2026-04-16 00:10:08.904232

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql


# revision identifiers, used by Alembic.
revision: str = '21b45f046656'
down_revision: Union[str, Sequence[str], None] = 'f69e15463d05'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('md_process', sa.Column('dynamic_attributes', mysql.JSON(), nullable=True, comment='柔性属性（JSON 对象）'))
    op.execute("ALTER TABLE md_process_resource MODIFY COLUMN resource_type ENUM('MATERIAL', 'EQUIPMENT', 'LABOR', 'TOOL', 'PROCESS') NOT NULL COMMENT '资源类型'")
    op.execute("ALTER TABLE md_resource_category MODIFY COLUMN resource_type ENUM('MATERIAL', 'EQUIPMENT', 'LABOR', 'TOOL', 'PROCESS') NOT NULL COMMENT '资源类型'")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TABLE md_resource_category MODIFY COLUMN resource_type ENUM('MATERIAL', 'EQUIPMENT', 'LABOR', 'TOOL') NOT NULL COMMENT '资源类型'")
    op.execute("ALTER TABLE md_process_resource MODIFY COLUMN resource_type ENUM('MATERIAL', 'EQUIPMENT', 'LABOR', 'TOOL') NOT NULL COMMENT '资源类型'")
    op.drop_column('md_process', 'dynamic_attributes')
    # ### end Alembic commands ###
