"""Refine master data models and snapshotted names

Revision ID: 9ed969162087
Revises: 21b45f046656
Create Date: 2026-04-16 01:30:04.805665

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '9ed969162087'
down_revision: Union[str, Sequence[str], None] = '21b45f046656'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('md_attr_definition', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_comment='创建时间',
               existing_nullable=False)
    op.alter_column('md_attr_definition', 'updated_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_comment='最后更新时间',
               existing_nullable=False)
    # op.drop_index(op.f('ix_md_attr_definition_unit_id'), table_name='md_attr_definition')
    op.alter_column('md_energy_calendar', 'name',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=50),
               comment='时段名称（如：峰时段、平时段、谷时段）',
               existing_comment='时段名称',
               existing_nullable=False)
    op.alter_column('md_energy_calendar', 'start_time',
               existing_type=mysql.TIME(),
               comment='开始时间（如：08:00:00）',
               existing_comment='开始时间',
               existing_nullable=False)
    op.alter_column('md_energy_calendar', 'end_time',
               existing_type=mysql.TIME(),
               comment='结束时间（如：12:00:00）',
               existing_comment='结束时间',
               existing_nullable=False)
    op.alter_column('md_energy_calendar', 'multiplier',
               existing_type=mysql.DECIMAL(precision=5, scale=2),
               server_default=None,
               nullable=False,
               comment='费率系数（如：峰时段 1.5，谷时段 0.5）',
               existing_comment='费率系数')
    op.alter_column('md_energy_calendar', 'is_active',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               existing_comment='是否启用',
               existing_server_default=sa.text("'1'"))
    op.alter_column('md_energy_calendar', 'id',
               existing_type=mysql.BIGINT(),
               comment='主键 ID',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('md_energy_calendar', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               nullable=False,
               existing_comment='创建时间')
    op.alter_column('md_energy_calendar', 'updated_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               nullable=False,
               comment='最后更新时间',
               existing_comment='更新时间')
    op.alter_column('md_energy_calendar', 'created_by',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=50),
               type_=sa.String(length=64),
               comment='创建人用户 ID',
               existing_comment='创建人',
               existing_nullable=True)
    op.alter_column('md_energy_calendar', 'updated_by',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=50),
               type_=sa.String(length=64),
               comment='最后操作人用户 ID',
               existing_comment='更新人',
               existing_nullable=True)
    op.alter_column('md_energy_calendar', 'is_deleted',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               comment='逻辑删除标志（1=已删除）',
               existing_comment='逻辑删除标记',
               existing_server_default=sa.text("'0'"))
    # op.drop_index(op.f('ix_md_energy_calendar_energy_rate_id'), table_name='md_energy_calendar')
    # op.drop_index(op.f('ix_md_energy_calendar_is_active'), table_name='md_energy_calendar')
    op.create_index(op.f('ix_md_energy_calendar_is_deleted'), 'md_energy_calendar', ['is_deleted'], unique=False)
    op.create_unique_constraint('uq_md_energy_calendar_rate_name_deleted', 'md_energy_calendar', ['energy_rate_id', 'name', 'is_deleted'])
    op.alter_column('md_energy_rate', 'energy_type',
               existing_type=mysql.ENUM('ELECTRICITY', 'WATER', 'GAS', 'STEAM', 'COMPRESSED_AIR', charset='utf8mb4', collation='utf8mb4_unicode_ci'),
               comment='能源类型（电/水/气/蒸汽/压缩空气）',
               existing_comment='能源类型',
               existing_nullable=False)
    op.alter_column('md_energy_rate', 'is_active',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               existing_comment='是否启用',
               existing_server_default=sa.text("'1'"))
    op.alter_column('md_energy_rate', 'id',
               existing_type=mysql.BIGINT(),
               comment='主键 ID',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('md_energy_rate', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               nullable=False,
               existing_comment='创建时间')
    op.alter_column('md_energy_rate', 'updated_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               nullable=False,
               comment='最后更新时间',
               existing_comment='更新时间')
    op.alter_column('md_energy_rate', 'created_by',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=50),
               type_=sa.String(length=64),
               comment='创建人用户 ID',
               existing_comment='创建人',
               existing_nullable=True)
    op.alter_column('md_energy_rate', 'updated_by',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=50),
               type_=sa.String(length=64),
               comment='最后操作人用户 ID',
               existing_comment='更新人',
               existing_nullable=True)
    op.alter_column('md_energy_rate', 'is_deleted',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               comment='逻辑删除标志（1=已删除）',
               existing_comment='逻辑删除标记',
               existing_server_default=sa.text("'0'"))
    # op.drop_index(op.f('ix_md_energy_rate_energy_type'), table_name='md_energy_rate')
    # op.drop_index(op.f('ix_md_energy_rate_is_active'), table_name='md_energy_rate')
    op.alter_column('md_equipment', 'code',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=50),
               comment='设备编码（业务唯一标识）',
               existing_comment='设备编码',
               existing_nullable=False)
    op.alter_column('md_equipment', 'category_id',
               existing_type=mysql.BIGINT(),
               comment='设备分类 ID',
               existing_nullable=True)
    op.alter_column('md_equipment', 'depreciation_rate',
               existing_type=mysql.DECIMAL(precision=10, scale=4),
               comment='静态折旧费率（元/小时）',
               existing_comment='静态折旧费率',
               existing_nullable=True)
    op.alter_column('md_equipment', 'power_consumption',
               existing_type=mysql.DECIMAL(precision=10, scale=4),
               comment='基础能耗系数（kW/h）',
               existing_comment='基础能耗系数',
               existing_nullable=True)
    op.alter_column('md_equipment', 'oee_target',
               existing_type=mysql.DECIMAL(precision=5, scale=2),
               comment='目标 OEE（%，如：85.5）',
               existing_comment='目标 OEE（%）',
               existing_nullable=True)
    op.alter_column('md_equipment', 'defect_rate',
               existing_type=mysql.DECIMAL(precision=5, scale=4),
               comment='标准缺陷率（%，如：0.5 表示 0.5%）',
               existing_comment='标准缺陷率（%）',
               existing_nullable=True)
    op.alter_column('md_equipment', 'dynamic_attributes',
               existing_type=mysql.JSON(),
               comment='柔性属性（JSON 对象，如：{"rated_power": 15.0, "spindle_speed": 3000}）',
               existing_comment='柔性属性',
               existing_nullable=True)
    op.alter_column('md_equipment', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_comment='创建时间',
               existing_nullable=False)
    op.alter_column('md_equipment', 'updated_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_comment='最后更新时间',
               existing_nullable=False)
    op.alter_column('md_equipment', 'is_deleted',
               existing_type=mysql.TINYINT(display_width=1),
               comment='逻辑删除标志（1=已删除）',
               existing_comment='逻辑删除标志',
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
    # op.drop_index(op.f('ix_md_equipment_category_id'), table_name='md_equipment')
    # op.drop_index(op.f('ix_md_equipment_is_active'), table_name='md_equipment')
    op.alter_column('md_labor', 'labor_type',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=50),
               comment='工种（如：焊工、电工、装配工）',
               existing_comment='工种',
               existing_nullable=True)
    op.alter_column('md_labor', 'skill_level',
               existing_type=mysql.ENUM('JUNIOR', 'INTERMEDIATE', 'SENIOR', 'MASTER', charset='utf8mb4', collation='utf8mb4_unicode_ci'),
               comment='技能等级（初/中/高/技师）',
               existing_comment='技能等级',
               existing_nullable=False)
    op.alter_column('md_labor', 'qualification_code',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=50),
               comment='资质编码（用于排产约束）',
               existing_comment='资质编码',
               existing_nullable=True)
    op.alter_column('md_labor', 'is_active',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               existing_comment='是否启用',
               existing_server_default=sa.text("'1'"))
    op.alter_column('md_labor', 'id',
               existing_type=mysql.BIGINT(),
               comment='主键 ID',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('md_labor', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               nullable=False,
               existing_comment='创建时间')
    op.alter_column('md_labor', 'updated_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               nullable=False,
               comment='最后更新时间',
               existing_comment='更新时间')
    op.alter_column('md_labor', 'created_by',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=50),
               type_=sa.String(length=64),
               comment='创建人用户 ID',
               existing_comment='创建人',
               existing_nullable=True)
    op.alter_column('md_labor', 'updated_by',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=50),
               type_=sa.String(length=64),
               comment='最后操作人用户 ID',
               existing_comment='更新人',
               existing_nullable=True)
    op.alter_column('md_labor', 'is_deleted',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               comment='逻辑删除标志（1=已删除）',
               existing_comment='逻辑删除标记',
               existing_server_default=sa.text("'0'"))
    # op.drop_index(op.f('ix_md_labor_category_id'), table_name='md_labor')
    # op.drop_index(op.f('ix_md_labor_is_active'), table_name='md_labor')
    # op.drop_index(op.f('ix_md_labor_skill_level'), table_name='md_labor')
    op.alter_column('md_material', 'code',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=50),
               comment='材料编码（业务唯一标识）',
               existing_comment='材料编码',
               existing_nullable=False)
    op.alter_column('md_material', 'category_id',
               existing_type=mysql.BIGINT(),
               comment='材料分类 ID',
               existing_nullable=True)
    op.alter_column('md_material', 'pricing_unit_id',
               existing_type=mysql.BIGINT(),
               comment='计价单位 ID',
               existing_nullable=True)
    op.alter_column('md_material', 'consumption_unit_id',
               existing_type=mysql.BIGINT(),
               comment='消耗单位 ID',
               existing_nullable=True)
    op.alter_column('md_material', 'loss_rate',
               existing_type=mysql.DECIMAL(precision=5, scale=2),
               comment='变动损耗率（%，如：5.5 表示 5.5%）',
               existing_comment='变动损耗率（%）',
               existing_nullable=True)
    op.alter_column('md_material', 'substitute_group',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=50),
               comment='替代料群组编码（同组材料可互换）',
               existing_comment='替代料群组编码',
               existing_nullable=True)
    op.alter_column('md_material', 'substitute_priority',
               existing_type=mysql.INTEGER(),
               comment='替代优先级（数字越小优先级越高）',
               existing_comment='替代优先级',
               existing_nullable=True)
    op.alter_column('md_material', 'dynamic_attributes',
               existing_type=mysql.JSON(),
               comment='柔性属性（JSON 对象，如：{"density": 7.85, "surface_treatment": "镀锌"}）',
               existing_comment='柔性属性',
               existing_nullable=True)
    op.alter_column('md_material', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_comment='创建时间',
               existing_nullable=False)
    op.alter_column('md_material', 'updated_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_comment='最后更新时间',
               existing_nullable=False)
    op.alter_column('md_material', 'is_deleted',
               existing_type=mysql.TINYINT(display_width=1),
               comment='逻辑删除标志（1=已删除）',
               existing_comment='逻辑删除标志',
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
    # op.drop_index(op.f('ix_md_material_category_id'), table_name='md_material')
    # op.drop_index(op.f('ix_md_material_is_active'), table_name='md_material')
    op.alter_column('md_process', 'is_active',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               existing_comment='是否启用',
               existing_server_default=sa.text("'1'"))
    op.alter_column('md_process', 'id',
               existing_type=mysql.BIGINT(),
               comment='主键 ID',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('md_process', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               nullable=False,
               existing_comment='创建时间')
    op.alter_column('md_process', 'updated_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               nullable=False,
               comment='最后更新时间',
               existing_comment='更新时间')
    op.alter_column('md_process', 'created_by',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=50),
               type_=sa.String(length=64),
               comment='创建人用户 ID',
               existing_comment='创建人',
               existing_nullable=True)
    op.alter_column('md_process', 'updated_by',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=50),
               type_=sa.String(length=64),
               comment='最后操作人用户 ID',
               existing_comment='更新人',
               existing_nullable=True)
    op.alter_column('md_process', 'is_deleted',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               comment='逻辑删除标志（1=已删除）',
               existing_comment='逻辑删除标记',
               existing_server_default=sa.text("'0'"))
    # op.drop_index(op.f('ix_md_process_category_id'), table_name='md_process')
    # op.drop_index(op.f('ix_md_process_is_active'), table_name='md_process')
    op.add_column('md_process_resource', sa.Column('resource_name', sa.String(length=100), nullable=True, comment='资源名称快照'))
    op.alter_column('md_process_resource', 'resource_type',
               existing_type=mysql.ENUM('MATERIAL', 'EQUIPMENT', 'LABOR', 'TOOL', 'PROCESS', collation='utf8mb4_unicode_ci'),
               comment='资源类型（EQUIPMENT/LABOR/MATERIAL/TOOL）',
               existing_comment='资源类型',
               existing_nullable=False)
    op.alter_column('md_process_resource', 'resource_id',
               existing_type=mysql.BIGINT(),
               comment='资源 ID（对应各资源表主键）',
               existing_comment='资源 ID',
               existing_nullable=False)
    op.alter_column('md_process_resource', 'quantity',
               existing_type=mysql.DECIMAL(precision=10, scale=4),
               server_default=None,
               nullable=False,
               existing_comment='消耗数量/投入比例')
    op.alter_column('md_process_resource', 'id',
               existing_type=mysql.BIGINT(),
               comment='主键 ID',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('md_process_resource', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               nullable=False,
               existing_comment='创建时间')
    op.alter_column('md_process_resource', 'updated_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               nullable=False,
               comment='最后更新时间',
               existing_comment='更新时间')
    op.alter_column('md_process_resource', 'created_by',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=50),
               type_=sa.String(length=64),
               comment='创建人用户 ID',
               existing_comment='创建人',
               existing_nullable=True)
    op.alter_column('md_process_resource', 'updated_by',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=50),
               type_=sa.String(length=64),
               comment='最后操作人用户 ID',
               existing_comment='更新人',
               existing_nullable=True)
    op.alter_column('md_process_resource', 'is_deleted',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               comment='逻辑删除标志（1=已删除）',
               existing_comment='逻辑删除标记',
               existing_server_default=sa.text("'0'"))
    # op.drop_index(op.f('ix_md_process_resource_process_id'), table_name='md_process_resource')
    # op.drop_index(op.f('ix_md_process_resource_type'), table_name='md_process_resource')
    op.create_index(op.f('ix_md_process_resource_is_deleted'), 'md_process_resource', ['is_deleted'], unique=False)
    op.alter_column('md_resource_category', 'code',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               comment='分类编码',
               existing_nullable=False)
    op.alter_column('md_resource_category', 'resource_type',
               existing_type=mysql.ENUM('MATERIAL', 'EQUIPMENT', 'LABOR', 'TOOL', 'PROCESS', collation='utf8mb4_unicode_ci'),
               comment='资源类型（MATERIAL/EQUIPMENT/LABOR/TOOL）',
               existing_comment='资源类型',
               existing_nullable=False)
    op.alter_column('md_resource_category', 'sort_order',
               existing_type=mysql.INTEGER(),
               server_default=None,
               comment='排序值，升序',
               existing_comment='排序值',
               existing_nullable=False)
    op.alter_column('md_resource_category', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_comment='创建时间',
               existing_nullable=False)
    op.alter_column('md_resource_category', 'updated_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_comment='最后更新时间',
               existing_nullable=False)
    op.alter_column('md_resource_category', 'is_deleted',
               existing_type=mysql.TINYINT(display_width=1),
               comment='逻辑删除标志（1=已删除）',
               existing_comment='逻辑删除标志',
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
    # op.drop_index(op.f('ix_md_resource_category_parent_id'), table_name='md_resource_category')
    # op.drop_index(op.f('ix_md_resource_category_resource_type'), table_name='md_resource_category')
    op.alter_column('md_unit', 'name',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=50),
               comment='单位名称（如：毫米、千克）',
               existing_comment='单位名称',
               existing_nullable=False)
    op.alter_column('md_unit', 'code',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=20),
               comment='单位编码（如：mm, kg）',
               existing_comment='单位编码',
               existing_nullable=False)
    op.alter_column('md_unit', 'symbol',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=10),
               comment='单位符号（如：mm, kg）',
               existing_comment='单位符号',
               existing_nullable=True)
    op.alter_column('md_unit', 'is_base',
               existing_type=mysql.TINYINT(display_width=1),
               comment='是否基础单位（如：米是长度的基础单位）',
               existing_comment='是否基础单位',
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('md_unit', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_comment='创建时间',
               existing_nullable=False)
    op.alter_column('md_unit', 'updated_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_comment='最后更新时间',
               existing_nullable=False)
    op.alter_column('md_unit', 'is_deleted',
               existing_type=mysql.TINYINT(display_width=1),
               comment='逻辑删除标志（1=已删除）',
               existing_comment='逻辑删除标志',
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('md_unit_conversion', 'conversion_factor',
               existing_type=mysql.DECIMAL(precision=20, scale=10),
               comment='换算因子（如：1吨 = 1000千克，因子为1000）',
               existing_comment='换算因子',
               existing_nullable=False)
    op.alter_column('md_unit_conversion', 'offset',
               existing_type=mysql.DECIMAL(precision=20, scale=10),
               comment='偏移量（用于温度等非线性换算，保留字段）',
               existing_comment='偏移量',
               existing_nullable=True)
    op.alter_column('md_unit_conversion', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_comment='创建时间',
               existing_nullable=False)
    op.alter_column('md_unit_conversion', 'updated_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_comment='最后更新时间',
               existing_nullable=False)
    op.alter_column('md_unit_conversion', 'is_deleted',
               existing_type=mysql.TINYINT(display_width=1),
               comment='逻辑删除标志（1=已删除）',
               existing_comment='逻辑删除标志',
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('md_unit_dimension', 'name',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=50),
               comment='量纲名称（如：长度、质量）',
               existing_comment='量纲名称',
               existing_nullable=False)
    op.alter_column('md_unit_dimension', 'code',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=30),
               comment='量纲编码（如：LENGTH, MASS）',
               existing_comment='量纲编码',
               existing_nullable=False)
    op.alter_column('md_unit_dimension', 'sort_order',
               existing_type=mysql.INTEGER(),
               server_default=None,
               comment='排序值，升序',
               existing_comment='排序值',
               existing_nullable=False)
    op.alter_column('md_unit_dimension', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_comment='创建时间',
               existing_nullable=False)
    op.alter_column('md_unit_dimension', 'updated_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_comment='最后更新时间',
               existing_nullable=False)
    op.alter_column('md_unit_dimension', 'is_deleted',
               existing_type=mysql.TINYINT(display_width=1),
               comment='逻辑删除标志（1=已删除）',
               existing_comment='逻辑删除标志',
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('org_department', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_comment='创建时间',
               existing_nullable=False)
    op.alter_column('org_department', 'updated_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_comment='最后更新时间',
               existing_nullable=False)
    op.alter_column('sys_audit_log', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_comment='记录时间',
               existing_nullable=False)
    op.alter_column('sys_dict_item', 'sort_order',
               existing_type=mysql.INTEGER(),
               server_default=None,
               existing_comment='排序值，升序',
               existing_nullable=False)
    op.alter_column('sys_dict_item', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_comment='创建时间',
               existing_nullable=False)
    op.alter_column('sys_dict_item', 'updated_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_comment='最后更新时间',
               existing_nullable=False)
    op.alter_column('sys_dict_type', 'sort_order',
               existing_type=mysql.INTEGER(),
               server_default=None,
               existing_comment='排序值，升序',
               existing_nullable=False)
    op.alter_column('sys_dict_type', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_comment='创建时间',
               existing_nullable=False)
    op.alter_column('sys_dict_type', 'updated_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_comment='最后更新时间',
               existing_nullable=False)
    op.alter_column('sys_permission', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_comment='创建时间',
               existing_nullable=False)
    op.alter_column('sys_permission', 'updated_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_comment='最后更新时间',
               existing_nullable=False)
    op.alter_column('sys_role', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_comment='创建时间',
               existing_nullable=False)
    op.alter_column('sys_role', 'updated_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_comment='最后更新时间',
               existing_nullable=False)
    op.alter_column('sys_role_permission', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_comment='创建时间',
               existing_nullable=False)
    op.alter_column('sys_role_permission', 'updated_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_comment='最后更新时间',
               existing_nullable=False)
    op.alter_column('sys_user', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_comment='创建时间',
               existing_nullable=False)
    op.alter_column('sys_user', 'updated_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_comment='最后更新时间',
               existing_nullable=False)
    op.alter_column('sys_user_role', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_comment='创建时间',
               existing_nullable=False)
    op.alter_column('sys_user_role', 'updated_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_comment='最后更新时间',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sys_user_role', 'updated_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('(now())'),
               existing_comment='最后更新时间',
               existing_nullable=False)
    op.alter_column('sys_user_role', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('(now())'),
               existing_comment='创建时间',
               existing_nullable=False)
    op.alter_column('sys_user', 'updated_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('(now())'),
               existing_comment='最后更新时间',
               existing_nullable=False)
    op.alter_column('sys_user', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('(now())'),
               existing_comment='创建时间',
               existing_nullable=False)
    op.alter_column('sys_role_permission', 'updated_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('(now())'),
               existing_comment='最后更新时间',
               existing_nullable=False)
    op.alter_column('sys_role_permission', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('(now())'),
               existing_comment='创建时间',
               existing_nullable=False)
    op.alter_column('sys_role', 'updated_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('(now())'),
               existing_comment='最后更新时间',
               existing_nullable=False)
    op.alter_column('sys_role', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('(now())'),
               existing_comment='创建时间',
               existing_nullable=False)
    op.alter_column('sys_permission', 'updated_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('(now())'),
               existing_comment='最后更新时间',
               existing_nullable=False)
    op.alter_column('sys_permission', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('(now())'),
               existing_comment='创建时间',
               existing_nullable=False)
    op.alter_column('sys_dict_type', 'updated_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_comment='最后更新时间',
               existing_nullable=False)
    op.alter_column('sys_dict_type', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_comment='创建时间',
               existing_nullable=False)
    op.alter_column('sys_dict_type', 'sort_order',
               existing_type=mysql.INTEGER(),
               server_default=sa.text("'0'"),
               existing_comment='排序值，升序',
               existing_nullable=False)
    op.alter_column('sys_dict_item', 'updated_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_comment='最后更新时间',
               existing_nullable=False)
    op.alter_column('sys_dict_item', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_comment='创建时间',
               existing_nullable=False)
    op.alter_column('sys_dict_item', 'sort_order',
               existing_type=mysql.INTEGER(),
               server_default=sa.text("'0'"),
               existing_comment='排序值，升序',
               existing_nullable=False)
    op.alter_column('sys_audit_log', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('(now())'),
               existing_comment='记录时间',
               existing_nullable=False)
    op.alter_column('org_department', 'updated_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('(now())'),
               existing_comment='最后更新时间',
               existing_nullable=False)
    op.alter_column('org_department', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('(now())'),
               existing_comment='创建时间',
               existing_nullable=False)
    op.alter_column('md_unit_dimension', 'is_deleted',
               existing_type=mysql.TINYINT(display_width=1),
               comment='逻辑删除标志',
               existing_comment='逻辑删除标志（1=已删除）',
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('md_unit_dimension', 'updated_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('(now())'),
               existing_comment='最后更新时间',
               existing_nullable=False)
    op.alter_column('md_unit_dimension', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('(now())'),
               existing_comment='创建时间',
               existing_nullable=False)
    op.alter_column('md_unit_dimension', 'sort_order',
               existing_type=mysql.INTEGER(),
               server_default=sa.text("'0'"),
               comment='排序值',
               existing_comment='排序值，升序',
               existing_nullable=False)
    op.alter_column('md_unit_dimension', 'code',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=30),
               comment='量纲编码',
               existing_comment='量纲编码（如：LENGTH, MASS）',
               existing_nullable=False)
    op.alter_column('md_unit_dimension', 'name',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=50),
               comment='量纲名称',
               existing_comment='量纲名称（如：长度、质量）',
               existing_nullable=False)
    op.alter_column('md_unit_conversion', 'is_deleted',
               existing_type=mysql.TINYINT(display_width=1),
               comment='逻辑删除标志',
               existing_comment='逻辑删除标志（1=已删除）',
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('md_unit_conversion', 'updated_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('(now())'),
               existing_comment='最后更新时间',
               existing_nullable=False)
    op.alter_column('md_unit_conversion', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('(now())'),
               existing_comment='创建时间',
               existing_nullable=False)
    op.alter_column('md_unit_conversion', 'offset',
               existing_type=mysql.DECIMAL(precision=20, scale=10),
               comment='偏移量',
               existing_comment='偏移量（用于温度等非线性换算，保留字段）',
               existing_nullable=True)
    op.alter_column('md_unit_conversion', 'conversion_factor',
               existing_type=mysql.DECIMAL(precision=20, scale=10),
               comment='换算因子',
               existing_comment='换算因子（如：1吨 = 1000千克，因子为1000）',
               existing_nullable=False)
    op.alter_column('md_unit', 'is_deleted',
               existing_type=mysql.TINYINT(display_width=1),
               comment='逻辑删除标志',
               existing_comment='逻辑删除标志（1=已删除）',
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('md_unit', 'updated_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('(now())'),
               existing_comment='最后更新时间',
               existing_nullable=False)
    op.alter_column('md_unit', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('(now())'),
               existing_comment='创建时间',
               existing_nullable=False)
    op.alter_column('md_unit', 'is_base',
               existing_type=mysql.TINYINT(display_width=1),
               comment='是否基础单位',
               existing_comment='是否基础单位（如：米是长度的基础单位）',
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('md_unit', 'symbol',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=10),
               comment='单位符号',
               existing_comment='单位符号（如：mm, kg）',
               existing_nullable=True)
    op.alter_column('md_unit', 'code',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=20),
               comment='单位编码',
               existing_comment='单位编码（如：mm, kg）',
               existing_nullable=False)
    op.alter_column('md_unit', 'name',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=50),
               comment='单位名称',
               existing_comment='单位名称（如：毫米、千克）',
               existing_nullable=False)
    op.create_index(op.f('ix_md_resource_category_resource_type'), 'md_resource_category', ['resource_type'], unique=False)
    op.create_index(op.f('ix_md_resource_category_parent_id'), 'md_resource_category', ['parent_id'], unique=False)
    op.alter_column('md_resource_category', 'is_deleted',
               existing_type=mysql.TINYINT(display_width=1),
               comment='逻辑删除标志',
               existing_comment='逻辑删除标志（1=已删除）',
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('md_resource_category', 'updated_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('(now())'),
               existing_comment='最后更新时间',
               existing_nullable=False)
    op.alter_column('md_resource_category', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('(now())'),
               existing_comment='创建时间',
               existing_nullable=False)
    op.alter_column('md_resource_category', 'sort_order',
               existing_type=mysql.INTEGER(),
               server_default=sa.text("'0'"),
               comment='排序值',
               existing_comment='排序值，升序',
               existing_nullable=False)
    op.alter_column('md_resource_category', 'resource_type',
               existing_type=mysql.ENUM('MATERIAL', 'EQUIPMENT', 'LABOR', 'TOOL', 'PROCESS', collation='utf8mb4_unicode_ci'),
               comment='资源类型',
               existing_comment='资源类型（MATERIAL/EQUIPMENT/LABOR/TOOL）',
               existing_nullable=False)
    op.alter_column('md_resource_category', 'code',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               comment=None,
               existing_comment='分类编码',
               existing_nullable=False)
    op.drop_index(op.f('ix_md_process_resource_is_deleted'), table_name='md_process_resource')
    op.create_index(op.f('ix_md_process_resource_type'), 'md_process_resource', ['resource_type'], unique=False)
    op.create_index(op.f('ix_md_process_resource_process_id'), 'md_process_resource', ['process_id'], unique=False)
    op.alter_column('md_process_resource', 'is_deleted',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True,
               comment='逻辑删除标记',
               existing_comment='逻辑删除标志（1=已删除）',
               existing_server_default=sa.text("'0'"))
    op.alter_column('md_process_resource', 'updated_by',
               existing_type=sa.String(length=64),
               type_=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=50),
               comment='更新人',
               existing_comment='最后操作人用户 ID',
               existing_nullable=True)
    op.alter_column('md_process_resource', 'created_by',
               existing_type=sa.String(length=64),
               type_=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=50),
               comment='创建人',
               existing_comment='创建人用户 ID',
               existing_nullable=True)
    op.alter_column('md_process_resource', 'updated_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('(now())'),
               nullable=True,
               comment='更新时间',
               existing_comment='最后更新时间')
    op.alter_column('md_process_resource', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('(now())'),
               nullable=True,
               existing_comment='创建时间')
    op.alter_column('md_process_resource', 'id',
               existing_type=mysql.BIGINT(),
               comment=None,
               existing_comment='主键 ID',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('md_process_resource', 'quantity',
               existing_type=mysql.DECIMAL(precision=10, scale=4),
               server_default=sa.text("'1.0000'"),
               nullable=True,
               existing_comment='消耗数量/投入比例')
    op.alter_column('md_process_resource', 'resource_id',
               existing_type=mysql.BIGINT(),
               comment='资源 ID',
               existing_comment='资源 ID（对应各资源表主键）',
               existing_nullable=False)
    op.alter_column('md_process_resource', 'resource_type',
               existing_type=mysql.ENUM('MATERIAL', 'EQUIPMENT', 'LABOR', 'TOOL', 'PROCESS', collation='utf8mb4_unicode_ci'),
               comment='资源类型',
               existing_comment='资源类型（EQUIPMENT/LABOR/MATERIAL/TOOL）',
               existing_nullable=False)
    op.drop_column('md_process_resource', 'resource_name')
    op.create_index(op.f('ix_md_process_is_active'), 'md_process', ['is_active'], unique=False)
    op.create_index(op.f('ix_md_process_category_id'), 'md_process', ['category_id'], unique=False)
    op.alter_column('md_process', 'is_deleted',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True,
               comment='逻辑删除标记',
               existing_comment='逻辑删除标志（1=已删除）',
               existing_server_default=sa.text("'0'"))
    op.alter_column('md_process', 'updated_by',
               existing_type=sa.String(length=64),
               type_=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=50),
               comment='更新人',
               existing_comment='最后操作人用户 ID',
               existing_nullable=True)
    op.alter_column('md_process', 'created_by',
               existing_type=sa.String(length=64),
               type_=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=50),
               comment='创建人',
               existing_comment='创建人用户 ID',
               existing_nullable=True)
    op.alter_column('md_process', 'updated_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('(now())'),
               nullable=True,
               comment='更新时间',
               existing_comment='最后更新时间')
    op.alter_column('md_process', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('(now())'),
               nullable=True,
               existing_comment='创建时间')
    op.alter_column('md_process', 'id',
               existing_type=mysql.BIGINT(),
               comment=None,
               existing_comment='主键 ID',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('md_process', 'is_active',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True,
               existing_comment='是否启用',
               existing_server_default=sa.text("'1'"))
    op.create_index(op.f('ix_md_material_is_active'), 'md_material', ['is_active'], unique=False)
    op.create_index(op.f('ix_md_material_category_id'), 'md_material', ['category_id'], unique=False)
    op.alter_column('md_material', 'is_deleted',
               existing_type=mysql.TINYINT(display_width=1),
               comment='逻辑删除标志',
               existing_comment='逻辑删除标志（1=已删除）',
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('md_material', 'updated_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('(now())'),
               existing_comment='最后更新时间',
               existing_nullable=False)
    op.alter_column('md_material', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('(now())'),
               existing_comment='创建时间',
               existing_nullable=False)
    op.alter_column('md_material', 'dynamic_attributes',
               existing_type=mysql.JSON(),
               comment='柔性属性',
               existing_comment='柔性属性（JSON 对象，如：{"density": 7.85, "surface_treatment": "镀锌"}）',
               existing_nullable=True)
    op.alter_column('md_material', 'substitute_priority',
               existing_type=mysql.INTEGER(),
               comment='替代优先级',
               existing_comment='替代优先级（数字越小优先级越高）',
               existing_nullable=True)
    op.alter_column('md_material', 'substitute_group',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=50),
               comment='替代料群组编码',
               existing_comment='替代料群组编码（同组材料可互换）',
               existing_nullable=True)
    op.alter_column('md_material', 'loss_rate',
               existing_type=mysql.DECIMAL(precision=5, scale=2),
               comment='变动损耗率（%）',
               existing_comment='变动损耗率（%，如：5.5 表示 5.5%）',
               existing_nullable=True)
    op.alter_column('md_material', 'consumption_unit_id',
               existing_type=mysql.BIGINT(),
               comment=None,
               existing_comment='消耗单位 ID',
               existing_nullable=True)
    op.alter_column('md_material', 'pricing_unit_id',
               existing_type=mysql.BIGINT(),
               comment=None,
               existing_comment='计价单位 ID',
               existing_nullable=True)
    op.alter_column('md_material', 'category_id',
               existing_type=mysql.BIGINT(),
               comment=None,
               existing_comment='材料分类 ID',
               existing_nullable=True)
    op.alter_column('md_material', 'code',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=50),
               comment='材料编码',
               existing_comment='材料编码（业务唯一标识）',
               existing_nullable=False)
    op.create_index(op.f('ix_md_labor_skill_level'), 'md_labor', ['skill_level'], unique=False)
    op.create_index(op.f('ix_md_labor_is_active'), 'md_labor', ['is_active'], unique=False)
    op.create_index(op.f('ix_md_labor_category_id'), 'md_labor', ['category_id'], unique=False)
    op.alter_column('md_labor', 'is_deleted',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True,
               comment='逻辑删除标记',
               existing_comment='逻辑删除标志（1=已删除）',
               existing_server_default=sa.text("'0'"))
    op.alter_column('md_labor', 'updated_by',
               existing_type=sa.String(length=64),
               type_=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=50),
               comment='更新人',
               existing_comment='最后操作人用户 ID',
               existing_nullable=True)
    op.alter_column('md_labor', 'created_by',
               existing_type=sa.String(length=64),
               type_=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=50),
               comment='创建人',
               existing_comment='创建人用户 ID',
               existing_nullable=True)
    op.alter_column('md_labor', 'updated_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('(now())'),
               nullable=True,
               comment='更新时间',
               existing_comment='最后更新时间')
    op.alter_column('md_labor', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('(now())'),
               nullable=True,
               existing_comment='创建时间')
    op.alter_column('md_labor', 'id',
               existing_type=mysql.BIGINT(),
               comment=None,
               existing_comment='主键 ID',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('md_labor', 'is_active',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True,
               existing_comment='是否启用',
               existing_server_default=sa.text("'1'"))
    op.alter_column('md_labor', 'qualification_code',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=50),
               comment='资质编码',
               existing_comment='资质编码（用于排产约束）',
               existing_nullable=True)
    op.alter_column('md_labor', 'skill_level',
               existing_type=mysql.ENUM('JUNIOR', 'INTERMEDIATE', 'SENIOR', 'MASTER', charset='utf8mb4', collation='utf8mb4_unicode_ci'),
               comment='技能等级',
               existing_comment='技能等级（初/中/高/技师）',
               existing_nullable=False)
    op.alter_column('md_labor', 'labor_type',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=50),
               comment='工种',
               existing_comment='工种（如：焊工、电工、装配工）',
               existing_nullable=True)
    op.create_index(op.f('ix_md_equipment_is_active'), 'md_equipment', ['is_active'], unique=False)
    op.create_index(op.f('ix_md_equipment_category_id'), 'md_equipment', ['category_id'], unique=False)
    op.alter_column('md_equipment', 'is_deleted',
               existing_type=mysql.TINYINT(display_width=1),
               comment='逻辑删除标志',
               existing_comment='逻辑删除标志（1=已删除）',
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('md_equipment', 'updated_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('(now())'),
               existing_comment='最后更新时间',
               existing_nullable=False)
    op.alter_column('md_equipment', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('(now())'),
               existing_comment='创建时间',
               existing_nullable=False)
    op.alter_column('md_equipment', 'dynamic_attributes',
               existing_type=mysql.JSON(),
               comment='柔性属性',
               existing_comment='柔性属性（JSON 对象，如：{"rated_power": 15.0, "spindle_speed": 3000}）',
               existing_nullable=True)
    op.alter_column('md_equipment', 'defect_rate',
               existing_type=mysql.DECIMAL(precision=5, scale=4),
               comment='标准缺陷率（%）',
               existing_comment='标准缺陷率（%，如：0.5 表示 0.5%）',
               existing_nullable=True)
    op.alter_column('md_equipment', 'oee_target',
               existing_type=mysql.DECIMAL(precision=5, scale=2),
               comment='目标 OEE（%）',
               existing_comment='目标 OEE（%，如：85.5）',
               existing_nullable=True)
    op.alter_column('md_equipment', 'power_consumption',
               existing_type=mysql.DECIMAL(precision=10, scale=4),
               comment='基础能耗系数',
               existing_comment='基础能耗系数（kW/h）',
               existing_nullable=True)
    op.alter_column('md_equipment', 'depreciation_rate',
               existing_type=mysql.DECIMAL(precision=10, scale=4),
               comment='静态折旧费率',
               existing_comment='静态折旧费率（元/小时）',
               existing_nullable=True)
    op.alter_column('md_equipment', 'category_id',
               existing_type=mysql.BIGINT(),
               comment=None,
               existing_comment='设备分类 ID',
               existing_nullable=True)
    op.alter_column('md_equipment', 'code',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=50),
               comment='设备编码',
               existing_comment='设备编码（业务唯一标识）',
               existing_nullable=False)
    op.create_index(op.f('ix_md_energy_rate_is_active'), 'md_energy_rate', ['is_active'], unique=False)
    op.create_index(op.f('ix_md_energy_rate_energy_type'), 'md_energy_rate', ['energy_type'], unique=False)
    op.alter_column('md_energy_rate', 'is_deleted',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True,
               comment='逻辑删除标记',
               existing_comment='逻辑删除标志（1=已删除）',
               existing_server_default=sa.text("'0'"))
    op.alter_column('md_energy_rate', 'updated_by',
               existing_type=sa.String(length=64),
               type_=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=50),
               comment='更新人',
               existing_comment='最后操作人用户 ID',
               existing_nullable=True)
    op.alter_column('md_energy_rate', 'created_by',
               existing_type=sa.String(length=64),
               type_=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=50),
               comment='创建人',
               existing_comment='创建人用户 ID',
               existing_nullable=True)
    op.alter_column('md_energy_rate', 'updated_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('(now())'),
               nullable=True,
               comment='更新时间',
               existing_comment='最后更新时间')
    op.alter_column('md_energy_rate', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('(now())'),
               nullable=True,
               existing_comment='创建时间')
    op.alter_column('md_energy_rate', 'id',
               existing_type=mysql.BIGINT(),
               comment=None,
               existing_comment='主键 ID',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('md_energy_rate', 'is_active',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True,
               existing_comment='是否启用',
               existing_server_default=sa.text("'1'"))
    op.alter_column('md_energy_rate', 'energy_type',
               existing_type=mysql.ENUM('ELECTRICITY', 'WATER', 'GAS', 'STEAM', 'COMPRESSED_AIR', charset='utf8mb4', collation='utf8mb4_unicode_ci'),
               comment='能源类型',
               existing_comment='能源类型（电/水/气/蒸汽/压缩空气）',
               existing_nullable=False)
    op.drop_constraint('uq_md_energy_calendar_rate_name_deleted', 'md_energy_calendar', type_='unique')
    op.drop_index(op.f('ix_md_energy_calendar_is_deleted'), table_name='md_energy_calendar')
    op.create_index(op.f('ix_md_energy_calendar_is_active'), 'md_energy_calendar', ['is_active'], unique=False)
    op.create_index(op.f('ix_md_energy_calendar_energy_rate_id'), 'md_energy_calendar', ['energy_rate_id'], unique=False)
    op.alter_column('md_energy_calendar', 'is_deleted',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True,
               comment='逻辑删除标记',
               existing_comment='逻辑删除标志（1=已删除）',
               existing_server_default=sa.text("'0'"))
    op.alter_column('md_energy_calendar', 'updated_by',
               existing_type=sa.String(length=64),
               type_=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=50),
               comment='更新人',
               existing_comment='最后操作人用户 ID',
               existing_nullable=True)
    op.alter_column('md_energy_calendar', 'created_by',
               existing_type=sa.String(length=64),
               type_=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=50),
               comment='创建人',
               existing_comment='创建人用户 ID',
               existing_nullable=True)
    op.alter_column('md_energy_calendar', 'updated_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('(now())'),
               nullable=True,
               comment='更新时间',
               existing_comment='最后更新时间')
    op.alter_column('md_energy_calendar', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('(now())'),
               nullable=True,
               existing_comment='创建时间')
    op.alter_column('md_energy_calendar', 'id',
               existing_type=mysql.BIGINT(),
               comment=None,
               existing_comment='主键 ID',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('md_energy_calendar', 'is_active',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True,
               existing_comment='是否启用',
               existing_server_default=sa.text("'1'"))
    op.alter_column('md_energy_calendar', 'multiplier',
               existing_type=mysql.DECIMAL(precision=5, scale=2),
               server_default=sa.text("'1.00'"),
               nullable=True,
               comment='费率系数',
               existing_comment='费率系数（如：峰时段 1.5，谷时段 0.5）')
    op.alter_column('md_energy_calendar', 'end_time',
               existing_type=mysql.TIME(),
               comment='结束时间',
               existing_comment='结束时间（如：12:00:00）',
               existing_nullable=False)
    op.alter_column('md_energy_calendar', 'start_time',
               existing_type=mysql.TIME(),
               comment='开始时间',
               existing_comment='开始时间（如：08:00:00）',
               existing_nullable=False)
    op.alter_column('md_energy_calendar', 'name',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=50),
               comment='时段名称',
               existing_comment='时段名称（如：峰时段、平时段、谷时段）',
               existing_nullable=False)
    op.create_index(op.f('ix_md_attr_definition_unit_id'), 'md_attr_definition', ['unit_id'], unique=False)
    op.alter_column('md_attr_definition', 'updated_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_comment='最后更新时间',
               existing_nullable=False)
    op.alter_column('md_attr_definition', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_comment='创建时间',
               existing_nullable=False)
    # ### end Alembic commands ###
