"""add unit_id to eng_bom_node

Revision ID: a2b3c4d5e6f7
Revises: e5f6g7h8i9j0
Create Date: 2026-04-21 10:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a2b3c4d5e6f7'
down_revision: Union[str, None] = 'de334e8f8425'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('eng_bom_node', sa.Column('unit_id', sa.BigInteger(), nullable=True, comment='单位 ID'))
    op.create_foreign_key('fk_eng_bom_node_unit_id', 'eng_bom_node', 'md_unit', ['unit_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_eng_bom_node_unit_id', 'eng_bom_node', type_='foreignkey')
    op.drop_column('eng_bom_node', 'unit_id')
    # ### end Alembic commands ###
