"""add process_type and outsource fields to eng_route_step_bind

Revision ID: b3c4d5e6f7g8
Revises: a2b3c4d5e6f7
Create Date: 2026-04-23 13:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b3c4d5e6f7g8'
down_revision: Union[str, None] = 'a2b3c4d5e6f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('eng_route_step_bind', sa.Column('process_type', sa.String(20), nullable=False, server_default='IN_HOUSE', comment='加工方式（IN_HOUSE=自制，OUTSOURCED=外协）'))
    op.add_column('eng_route_step_bind', sa.Column('override_equipment_id', sa.BigInteger(), nullable=True, comment='覆写设备 ID（自制时使用）'))
    op.add_column('eng_route_step_bind', sa.Column('outsource_price', sa.Numeric(10, 2), nullable=True, comment='外协单价（外协时使用）'))
    op.create_foreign_key('fk_eng_route_step_bind_equipment_id', 'eng_route_step_bind', 'md_equipment', ['override_equipment_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_eng_route_step_bind_equipment_id', 'eng_route_step_bind', type_='foreignkey')
    op.drop_column('eng_route_step_bind', 'outsource_price')
    op.drop_column('eng_route_step_bind', 'override_equipment_id')
    op.drop_column('eng_route_step_bind', 'process_type')
    # ### end Alembic commands ###
