"""init_system_tables

Revision ID: df78acee9fdf
Revises: 
Create Date: 2026-04-14 21:58:23.323357

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df78acee9fdf'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('org_department',
    sa.Column('name', sa.String(length=100), nullable=False, comment='部门名称'),
    sa.Column('code', sa.String(length=50), nullable=False, comment='部门编码'),
    sa.Column('parent_id', sa.BigInteger(), nullable=True, comment='父部门 ID'),
    sa.Column('sort_order', sa.Integer(), nullable=False, comment='排序值，升序'),
    sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False, comment='是否启用'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主键 ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='最后更新时间'),
    sa.Column('created_by', sa.String(length=64), nullable=True, comment='创建人用户 ID'),
    sa.Column('updated_by', sa.String(length=64), nullable=True, comment='最后操作人用户 ID'),
    sa.Column('is_deleted', sa.Boolean(), server_default='0', nullable=False, comment='逻辑删除标志（1=已删除）'),
    sa.ForeignKeyConstraint(['parent_id'], ['org_department.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index(op.f('ix_org_department_is_deleted'), 'org_department', ['is_deleted'], unique=False)
    op.create_table('sys_audit_log',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True, comment='操作人用户 ID'),
    sa.Column('username', sa.String(length=64), nullable=True, comment='操作人用户名（快照）'),
    sa.Column('action', sa.String(length=50), nullable=False, comment='操作动作（CREATE/UPDATE/DELETE/LOGIN）'),
    sa.Column('resource_type', sa.String(length=100), nullable=True, comment='操作对象类型'),
    sa.Column('resource_id', sa.String(length=64), nullable=True, comment='操作对象 ID'),
    sa.Column('detail', sa.Text(), nullable=True, comment='操作详情（JSON 字符串）'),
    sa.Column('ip_address', sa.String(length=50), nullable=True, comment='客户端 IP'),
    sa.Column('user_agent', sa.String(length=512), nullable=True, comment='User-Agent'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='记录时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sys_permission',
    sa.Column('name', sa.String(length=64), nullable=False, comment='权限显示名称'),
    sa.Column('code', sa.String(length=100), nullable=False, comment='权限唯一编码'),
    sa.Column('resource', sa.String(length=200), nullable=False, comment='资源路径（如 /api/v1/materials）'),
    sa.Column('action', sa.String(length=20), nullable=False, comment='操作类型：read/write/delete/admin'),
    sa.Column('description', sa.String(length=256), nullable=True, comment='权限描述'),
    sa.Column('parent_id', sa.BigInteger(), nullable=True, comment='父权限 ID（用于菜单分组）'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主键 ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='最后更新时间'),
    sa.Column('created_by', sa.String(length=64), nullable=True, comment='创建人用户 ID'),
    sa.Column('updated_by', sa.String(length=64), nullable=True, comment='最后操作人用户 ID'),
    sa.Column('is_deleted', sa.Boolean(), server_default='0', nullable=False, comment='逻辑删除标志（1=已删除）'),
    sa.ForeignKeyConstraint(['parent_id'], ['sys_permission.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index(op.f('ix_sys_permission_is_deleted'), 'sys_permission', ['is_deleted'], unique=False)
    op.create_table('sys_role',
    sa.Column('name', sa.String(length=64), nullable=False, comment='角色显示名称'),
    sa.Column('code', sa.String(length=50), nullable=False, comment='角色唯一编码（程序内使用）'),
    sa.Column('description', sa.String(length=256), nullable=True, comment='角色描述'),
    sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False, comment='是否启用'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主键 ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='最后更新时间'),
    sa.Column('created_by', sa.String(length=64), nullable=True, comment='创建人用户 ID'),
    sa.Column('updated_by', sa.String(length=64), nullable=True, comment='最后操作人用户 ID'),
    sa.Column('is_deleted', sa.Boolean(), server_default='0', nullable=False, comment='逻辑删除标志（1=已删除）'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_sys_role_is_deleted'), 'sys_role', ['is_deleted'], unique=False)
    op.create_table('sys_role_permission',
    sa.Column('role_id', sa.BigInteger(), nullable=False, comment='角色 ID'),
    sa.Column('permission_id', sa.BigInteger(), nullable=False, comment='权限 ID'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主键 ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='最后更新时间'),
    sa.Column('created_by', sa.String(length=64), nullable=True, comment='创建人用户 ID'),
    sa.Column('updated_by', sa.String(length=64), nullable=True, comment='最后操作人用户 ID'),
    sa.Column('is_deleted', sa.Boolean(), server_default='0', nullable=False, comment='逻辑删除标志（1=已删除）'),
    sa.ForeignKeyConstraint(['permission_id'], ['sys_permission.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['sys_role.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('role_id', 'permission_id', name='uq_role_permission')
    )
    op.create_index(op.f('ix_sys_role_permission_is_deleted'), 'sys_role_permission', ['is_deleted'], unique=False)
    op.create_table('sys_user',
    sa.Column('username', sa.String(length=64), nullable=False, comment='登录用户名'),
    sa.Column('hashed_password', sa.String(length=256), nullable=False, comment='bcrypt 密码哈希'),
    sa.Column('real_name', sa.String(length=64), nullable=False, comment='真实姓名'),
    sa.Column('email', sa.String(length=128), nullable=True, comment='邮箱'),
    sa.Column('phone', sa.String(length=20), nullable=True, comment='手机号'),
    sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False, comment='账号是否启用'),
    sa.Column('department_id', sa.BigInteger(), nullable=True, comment='所属部门 ID'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主键 ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='最后更新时间'),
    sa.Column('created_by', sa.String(length=64), nullable=True, comment='创建人用户 ID'),
    sa.Column('updated_by', sa.String(length=64), nullable=True, comment='最后操作人用户 ID'),
    sa.Column('is_deleted', sa.Boolean(), server_default='0', nullable=False, comment='逻辑删除标志（1=已删除）'),
    sa.ForeignKeyConstraint(['department_id'], ['org_department.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_index(op.f('ix_sys_user_is_deleted'), 'sys_user', ['is_deleted'], unique=False)
    op.create_table('sys_user_role',
    sa.Column('user_id', sa.BigInteger(), nullable=False, comment='用户 ID'),
    sa.Column('role_id', sa.BigInteger(), nullable=False, comment='角色 ID'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主键 ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='最后更新时间'),
    sa.Column('created_by', sa.String(length=64), nullable=True, comment='创建人用户 ID'),
    sa.Column('updated_by', sa.String(length=64), nullable=True, comment='最后操作人用户 ID'),
    sa.Column('is_deleted', sa.Boolean(), server_default='0', nullable=False, comment='逻辑删除标志（1=已删除）'),
    sa.ForeignKeyConstraint(['role_id'], ['sys_role.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['sys_user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'role_id', name='uq_user_role')
    )
    op.create_index(op.f('ix_sys_user_role_is_deleted'), 'sys_user_role', ['is_deleted'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sys_user_role_is_deleted'), table_name='sys_user_role')
    op.drop_table('sys_user_role')
    op.drop_index(op.f('ix_sys_user_is_deleted'), table_name='sys_user')
    op.drop_table('sys_user')
    op.drop_index(op.f('ix_sys_role_permission_is_deleted'), table_name='sys_role_permission')
    op.drop_table('sys_role_permission')
    op.drop_index(op.f('ix_sys_role_is_deleted'), table_name='sys_role')
    op.drop_table('sys_role')
    op.drop_index(op.f('ix_sys_permission_is_deleted'), table_name='sys_permission')
    op.drop_table('sys_permission')
    op.drop_table('sys_audit_log')
    op.drop_index(op.f('ix_org_department_is_deleted'), table_name='org_department')
    op.drop_table('org_department')
    # ### end Alembic commands ###
